### PR TITLE
support locale 4(zhCN)

### PR DESCRIPTION
**Pull request by qyh214**
**Changes proposed**:

- merge 721907db72bd7c02aae59f6db309ebf6364adccd (branch:locale4) to c61fb787aee19a37cda4e4cc41911dc5e1cb36c6 (branch:master)  and fix 
- add includes/types/* loc4
- add template/localized/* loc4
- add pages/* loc4
- fix some zhcn.php zhcn.js wrong translation(zhCN)
- Added a large amount of translation(zhCN)
- add footer to all pages

**Issues addressed**: none

**Tests performed**: tested and you can see http://qyh.qyh.name:214/aowow/

**Known issues and TODO list**:

- [ ] sounds and icons locale??: IF EXISTS zhcn/sounds/* , zhcn/interface/icons/* , when `php aowow --firstrun` to build and it will cause issue:sounds and icons will show empty(now I only set enus sounds and icons and empty zhcn sounds and icons then build well，shows well) .so I  guess sounds and icons not support localization.

- [x] DB.aowow_currencies missing description_loc* read ,please check setup\tools\sqlgen\currencies.func.php

### CODE REVIEW

**Comment by Sarjuuk** [comment]
Just a few things before i read into this (which may take couple of days, because i'm currently on the move)

Any translation from my side was either taken from wowhead (about version 6.2.3) or the GlobalStrings.lua (version 3.3.5.13507 (dunno why the build number is not 12340))
If you replace something translated by wowhead, fine. But actual game strings i'm likely to keep like they are, for consistency sake. It's hard to tell what is what from time to time though. :/

For the time being, sounds are not multilingual. Though, if the sound setup fails for the chinese client, i'll have to look into that. (that part wasn't clear to me)

There are no descriptions for currencies in 3.3.5. You can get them from later clients and add them manually.

**Comment by qyh214** [comment]
**translation**:
The baseline order for my translation is:
GlobalStrings.lua = zhcn/DBC > cn.wowhead,com/wow.178.com(some Large scale World of Warcraft professional database query website in China) = Languages used by World of Warcraft players in China > myself.
so I believe we are consistent with the translation objectives and as far as possible Blizzlike.

**sounds/icons Multinational support**:
If this is a future feature, you can set it as a separate issue and you can delete this todo in this pull request.
I think sound setup is well,because I copy all zhcn/sounds into enus/sounds and delete zhcn/sounds and setup very well!(Similarly icons).

Finally, when you have time, review the code and merge to master.Next, I just need to submit a translation file to you separately(zhcn.php and zhcn.js)

**Comment by lyrl** [comment]
楼主使用的是什么版本的中文客户端

**Comment by Sarjuuk** [comment]
You are not expecting me to understand that, are you?

**Comment by lyrl** [comment]
When is code merged?

**Comment by peycho** [comment]
What should be updated on this PR?

**Comment by Sarjuuk** [comment]
in case anyone is still subscribed here.

* by and large i am done with translating (read: copying strings of random glyphs from wowhead, GlobalStrings.lua and assorted dbc-files (client build used was 13507) if anyone takes issue with anything, now is the time to pitch in why anything needs change.
* there are still a lot of strings missing. Mostly custom and deprecated stuff that i cannot get translated anymore but will merge anyway if no changes are proposed.
* i will commit [this](https://github.com/Sarjuuk/aowow/pull/119/commits/9edc14079fc5440607e21cd3849a5a2fa5370754#diff-6db445d880f15f5e5ffcb9b84bf5d6fa) only, if appropriate element selectors are set. no blanket *
* i still don't know whats wrong with extracting icons or sound (they are not localized?)
* not every page needs a footer

**Comment by Sarjuuk** [comment]
implemented in 761da59ee9307f4aa0a70c558a038c483008c335

**Comment by lyrl** [comment]
@Sarjuuk thank you

**Pull request closed without merging**
