### PR TITLE
Update credits

### PR DESCRIPTION
**Pull request by Helias**

### CODE REVIEW

**Comment by Sarjuuk** [comment]
hah!

honestly, i'd feel bad for patting myself on the back like that

**Comment by Helias** [comment]
I can understand, indeed, I am doing for you xD

**Comment by Sarjuuk** [comment]
please fix the typo 
(and add the readability changes you mentioned (if you want to))

**Comment by Helias** [comment]
??

I already added the readability changes, that's the main reason for this PR xD 

before:
image

after:
image

**Pull request merged**
